### ISSUE TITLE
PowerDNS mock server

### ISSUE THREAD

**Issue by skunkie** [joeig/go-powerdns#26]
Is it possible to make a PowerDNS mock server based on the tests?

**Comment by lwhile** [comment]
You can implement it by yourself and it's easily to do that

**Comment by joeig** [comment]
I've actually started to write a standalone mock server in [refactorMocksTypes](https://github.com/joeig/go-powerdns/tree/refactorMocksTypes) in 2020, but I haven't been able to finish it so far. If you decide to work on it, I would appreciate a pull request.
