### ISSUE TITLE
Proposal: Return response from zone/record CRUD operations

### ISSUE THREAD

**Issue by circa10a** [joeig/go-powerdns#58]
Hello!

Firstly, thank you for this awesome library! I wanted to pick your brain about the idea of a breaking change which is to return an `*http.Response` in addition to an error from record/zone CRUD operations.

We have a use case to log request ID response headers for tracing when making PDNS calls which isn't possible today without providing a custom `*http.Client` + transport. There may be other, more appropriate approaches that you're aware of that I am not.  If so, I would love to hear your insight.

Today's implementation:

```go
err := client.Records.Add(
		ctx,
		record.Zone,
		record.FQDN,
		recordType,
		uint32(record.TTL),
		record.Targets,
	)
	if err != nil {
		return err
	}
```

Proposal:

```go
response, err := client.Records.Add(
		ctx,
		record.Zone,
		record.FQDN,
		recordType,
		uint32(record.TTL),
		record.Targets,
	)
	if err != nil {
		return err
	}
```

Curious on your thoughts on the matter 😃 
Thank you again!

**Comment by circa10a** [comment]
I think this would also satisfy my use case. Do you think it's worth adding examples to the documentation?

**Comment by circa10a** [comment]
Here's an example if anyone comes looking:

```go
type loggingTransport struct{}

func (l *loggingTransport) RoundTrip(r *http.Request) (*http.Response, error) {
	resp, err := http.DefaultTransport.RoundTrip(r)

	requestID := resp.Header.Get("X-Request-Id")
	if requestID != "" {
		fmt.Println("Request made. requestId: ", requestID)
	} else {
		fmt.Println("Request made. No requestId found")
	}

	return resp, err
}

// NewClient returns a new PDNS client
func NewClient(apiKey, endpoint string) *pdns.Client {
	httpClient := &http.Client{
		Timeout:   time.Second * 10,
		Transport: &loggingTransport{},
	}
	return pdns.NewClient(
		endpoint,
		"",
		map[string]string{
			"Authorization": "Bearer " + apiKey,
			"X-API-KEY":     apiKey,
		},
		httpClient)
}
```

**Comment by joeig** [comment]
Thanks for the example code. Feel free to file a PR with a [testable Godoc example](https://go.dev/blog/examples).
