### ISSUE TITLE
Support query parameters on fetching rrsets

### ISSUE THREAD

**Issue by tnsimon** [joeig/go-powerdns#62]
https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones-zone_id

The Power DNS API supports filtering by the following query params. Would be great to support this via the RecordsService. Happy to contribute this addition.

> rrsets (boolean) – “true” (default) or “false”, whether to include the “rrsets” in the response Zone object.
> rrset_name (string) – Limit output to RRsets for this name.
> rrset_type (string) – Limit output to the RRset of this type. Can only be used together with rrset_name.

**Comment by joeig** [comment]
Let's go
