### ISSUE TITLE
Support comments when adding records

### ISSUE THREAD

**Issue by 42wim** [joeig/go-powerdns#66]
It would be handy to add comments and owner when creating records

I'm willing to create a PR from this, but I'm not sure if you want to support this and how you want to call your methods
I've created a quick fix for a project of mine: https://github.com/42wim/go-powerdns/commit/5727ba7e21b4214dede5e0f2399705c0694bd8c1

**Comment by joeig** [comment]
I suggest extending the existing `Change` methods with the options pattern instead of having additional `ChangeWithComment` methods.

**Comment by joeig** [comment]
Anyway, I look forward to your PR if you want to work on it.

**Comment by verscheures** [comment]
Since I needed this feature myself I Added it on my fork using the options pattern,  https://github.com/verscheures/go-powerdns/tree/feat/add-comments-to-record-calls

If its ok, i'll create a PR for it.

**Comment by joeig** [comment]
LGTM, can you create a PR?
